baseURL = 'https://jeffcheng.github.io/'
languageCode = 'en-us'
title = 'My Blog'
theme = "tale"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0
[Author]
    name = "H.T.Cheng"

[Params]
css = ["custom.css"]